spring.config.activate.on-profile: local

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    defer-datasource-initialization: true
---
spring.config.activate.on-profile: prod

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cafe
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: rootuser
